
services:
  backend:
    build: ./backend
    container_name: fastapi_app
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    networks:
      - apisrvs

#  frontend:
#    build: ./frontend
#    container_name: react_app
#    restart: always
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"
#    networks:
#      - frontend

networks:
  apisrvs:
    external: true
#  frontend:
#    driver: bridge
#
#volumes:
#  pg_data:
