"""Initital revision

Revision ID: 1c8a68131571
Revises: 
Create Date: 2025-02-24 15:44:10.972268

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '1c8a68131571'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
