"""Fixed relationship back_populates in TaskQueue

Revision ID: 6c0d29f89467
Revises: 6a19ea7f6aac
Create Date: 2025-03-15 16:29:04.019203

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6c0d29f89467"
down_revision: Union[str, None] = "6a19ea7f6aac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks_queue",
        "error_stage",
        existing_type=sa.Enum(
            "VALIDATING",
            "PARSING",
            "FILTERING",
            "REPORTING",
            "MOVING",
            name="taskprocessingstage",
        ),
        type_=postgresql.ENUM(
            "VALIDATING",
            "PARSING",
            "FILTERING",
            "REPORTING",
            "MOVING",
            name="task_processing_stage",
        ),
        existing_nullable=True,
    )
    op.alter_column(
        "tasks_queue",
        "status",
        existing_type=sa.Enum(
            "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="taskstatus"
        ),
        type_=postgresql.ENUM(
            "PENDING", "IN_PROGRESS", "COMPLETED", "FAILED", name="task_status"
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
