"""Add TaskQueue model, Del fields in SourceFile model

Revision ID: 88137cde4f15
Revises: 4f941e4abcf2
Create Date: 2025-03-14 16:08:47.508225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "88137cde4f15"
down_revision: Union[str, None] = "4f941e4abcf2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("source_files", "error_stage")
    op.drop_column("source_files", "error_message")
    op.drop_column("source_files", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_files",
        sa.Column(
            "status",
            postgresql.ENUM(
                "NEW",
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="processingstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "source_files",
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "source_files",
        sa.Column("error_stage", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
